name: pager
description: Widget switching pages based on stream
version: 0.0.2-dev.0
author: PlugFox
homepage: https://github.com/plugfox/pager

environment:
  sdk: ^2.12.0
  flutter: ^2.0.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
