name: pager
description: Widget switching pages based on stream
version: 0.0.1-dev
author: PlugFox
homepage: https://github.com/plugfox/pager

environment:
  sdk: ">=2.10.0 <3.0.0"
  flutter: ">=1.23.0-13.0.pre <1.24.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
